=== Alakni0/Alakni0.github.io/dane.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="faktura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nabywca">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="imie" type="xs:string"/>
                            <xs:element name="nazwisko" type="xs:string"/>
                            <xs:element name="adres" type="xs:string"/>
                            <xs:element name="nip" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="usluga" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nazwa" type="xs:string"/>
                            <xs:element name="ilosc" type="xs:decimal"/>
                            <xs:element name="cena" type="xs:decimal"/>
                            <xs:element name="wartosc" type="xs:decimal"/>
                            <xs:element name="kwota" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Alakni0/Alakni0.github.io/dane.xml
<?xml version="1.0" encoding="UTF-8"?>
<faktura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="dane.xsd">
    <nabywca>
        <imie>Zdziś</imie>
        <nazwisko>Zdzisiowaty</nazwisko>
        <adres>ul. Miła 10, 21-500 Biala Podlaska</adres>
        <nip>123-456-78-90</nip>
    </nabywca>
    <usluga>
        <nazwa>Delfin gumowy</nazwa>
        <ilosc>20</ilosc>
        <cena>50</cena>
        <wartosc>1000</wartosc>
        <kwota>230</kwota>
    </usluga>
    <usluga>
        <nazwa>Delfin kałczukowy</nazwa>
        <ilosc>20</ilosc>
        <cena>60</cena>
        <wartosc>1200</wartosc>
        <kwota>276</kwota>
    </usluga>
    <usluga>
        <nazwa>Delfin z mydła</nazwa>
        <ilosc>20</ilosc>
        <cena>300</cena>
        <wartosc>6000</wartosc>
        <kwota>1380</kwota>
    </usluga>
</faktura>
